# ================================
# Server & Application config
# ================================
server.port=8810
spring.application.name=product-catalog-service

# ================================
# Eureka Discovery
# ================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ================================
# SQL Server Data Source
# ================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=products;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=Test1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ================================
# JPA / Hibernate
# ================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

# ================================
# Multipart config
# ================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# --- CẤU HÌNH GEMINI AI ---
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent