# ================================
# Server & Application config
# ================================
server.port=8810
spring.application.name=product-catalog-service

# ================================
# Eureka Discovery
# ================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ================================
# SQL Server Data Source
# ================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=products;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Test1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ================================
# JPA / Hibernate
# ================================
spring.jpa.show-sql=true
# ĐÃ SỬA: Lùi về SQLServer2012Dialect để tương thích với Spring Boot 2.1.5
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

# ================================
# Multipart config
# ================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB